# Generated by Django 4.1.5 on 2024-09-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='ativo',
            field=models.CharField(editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='celular_01',
            field=models.CharField(editable=False, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='celular_02',
            field=models.CharField(editable=False, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='responsavel_01',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='responsavel_02',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='tipo',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
