# Generated by Django 4.1.5 on 2024-09-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_comunidade_ativo_comunidade_celular_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidade',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
