# Generated by Django 4.1.5 on 2024-09-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cidade_comunidade',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='nome_comunidade_str',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
