# Generated by Django 4.1.5 on 2024-09-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_comunidade_cnpj'),
        ('usuarios', '0002_users_cidade_comunidade_users_nome_comunidade_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cargo',
            field=models.CharField(choices=[('V', 'Vendedor'), ('R', 'Responsavel Geral'), ('A', 'Admin'), ('T', 'Trocar_Senha')], max_length=2),
        ),
        migrations.AlterField(
            model_name='users',
            name='nome_comunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.comunidade'),
        ),
    ]
