# Generated by Django 4.1.5 on 2024-09-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_users_cargo_alter_users_nome_comunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cargo',
            field=models.CharField(choices=[('V', 'Vendedor'), ('R', 'responsavel_geral'), ('A', 'Admin'), ('T', 'Trocar_Senha')], max_length=2),
        ),
    ]
